import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:money_management/constants/color_constant.dart';
import 'package:money_management/constants/material.dart';
import 'package:money_management/domain/moneys/entities/money_model.dart';
import 'package:money_management/domain/moneys/entities/money_type.dart';
import 'package:money_management/hives/hive_constant.dart';
import 'package:money_management/hives/hive_utils.dart';
import 'package:money_management/models/event_model.dart';
import 'package:money_management/pages/analysis/bloc/analysis_bloc.dart';
import 'package:money_management/pages/calendar/bloc/calendar_bloc.dart';
import 'package:money_management/pages/setting/bloc/setting_bloc.dart';
import 'package:money_management/utils/datetime_utils.dart';
import 'package:money_management/utils/format_utils.dart';
import 'package:table_calendar/table_calendar.dart';
import 'package:flutter_gen/gen_l10n/app_localizations.dart';

part 'calendar_screen.dart';
